const WordsMap = {
  enName: [
    "jake",
    "Alice",
    "dave",
    "David",
    "John",
    "Michael",
    "Emily",
    "Sarah",
    "Robert",
    "Jessica",
    "Daniel",
    "Laura",
    "Thomas",
    "Amanda",
    "James",
    "Rachel",
    "Matthew",
    "Olivia",
    "Andrew",
    "Hannah",
    "Joseph",
    "Sophia",
    "Mark",
    "Emma",
    "Steven",
    "Grace",
    "Kevin",
    "Chloe",
    "Brian",
    "Natalie",
    "Eric",
    "Julia",
    "Anthony",
    "Victoria",
    "Joshua",
    "Abigail",
    "George",
    "Samantha",
    "Benjamin",
    "Isabella",
    "Samuel",
    "Zoe",
    "Henry",
    "Lily",
  ],
  enColor: [
    "blue",
    "red",
    "green",
    "yellow",
    "pink",
    "black",
    "brown",
    "gray",
    "orange",
    "whitle",
    "purple",
    "cyan",
    "magenta",
    "lime",
    "teal",
    "indigo",
    "violet",
    "gold",
    "silver",
    "maroon",
    "navy",
    "olive",
    "coral",
    "salmon",
    "turquoise",
    "plum",
    "orchid",
    "chocolate",
    "crimson",
    "skyblue",
    "lavender",
    "beige",
    "mint",
    "peach",
    "khaki",
  ],
  enfruits: [
    "apple",
    "orange",
    "blueberry",
    "Strawberry",
    "cucumber",
    "orange",
    "banana",
    "lemon",
    "grapes",
    "pineapple",
    "mango",
    "pear",
    "peach",
    "watermelon",
    "cherry",
    "plum",
    "pomegranate",
    "kiwi",
    "apricot",
    "fig",
    "lime",
    "papaya",
    "coconut",
    "raspberry",
    "blackberry",
    "guava",
    "nectarine",
    "passionfruit",
    "dragonfruit",
  ],
  enJobs: [
    "police",
    "teacher",
    "student",
    "firefighter",
    "businessman",
    "Driver",
    "worker",
    "nurse",
    "doctor",
    "programmer",
    "engineer",
    "chef",
    "mechanic",
    "plumber",
    "electrician",
    "architect",
    "scientist",
    "pilot",
    "flight attendant",
    "farmer",
    "photographer",
    "artist",
    "musician",
    "actor",
    "dancer",
    "lawyer",
    "judge",
    "accountant",
    "dentist",
    "veterinarian",
    "pharmacist",
    "cashier",
    "librarian",
    "translator",
    "receptionist",
    "security guard",
    "data analyst",
    "IT specialist",
    "web developer",
    "barber",
    "hairdresser",
    "fashion designer",
    "salesperson",
    "real estate agent",
    "coach",
    "athlete",
    "journalist",
    "news anchor",
    "editor",
    "publisher",
    "painter",
    "construction worker",
    "delivery driver",
    "janitor",
    "social worker",
    "consultant",
    "tour guide",
    "waiter",
    "bakery chef",
    "marketing manager",
  ],
  enSubjects: [
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "English Literature",
    "History",
    "Geography",
    "Computer Science",
    "Economics",
    "Philosophy",
    "Psychology",
    "Sociology",
    "Political Science",
    "Art",
    "Music",
    "Physical Education",
    "Environmental Science",
    "Business Studies",
    "Accounting",
    "Law",
    "Statistics",
    "French",
    "Spanish",
    "German",
    "Chinese",
    "Arabic",
    "Religious Studies",
    "Drama",
    "Health Education",
    "Design and Technology",
  ],
  enBodyProblem: [
    "flu",
    "cold",
    "diabetes",
    "hypertension",
    "asthma",
    "bronchitis",
    "pneumonia",
    "migraine",
    "depression",
    "anxiety",
    "arthritis",
    "osteoporosis",
    "eczema",
    "psoriasis",
    "tuberculosis",
    "hepatitis",
    "HIV",
    "AIDS",
    "cancer",
    "leukemia",
    "malaria",
    "measles",
    "mumps",
    "chickenpox",
    "covid-19",
    "stroke",
    "heart attack",
    "obesity",
    "ulcer",
    "appendicitis",
    "kidney stones",
    "gallstones",
    "thyroid disorder",
    "autism",
    "bipolar disorder",
    "schizophrenia",
    "parkinson's disease",
    "alzheimer's disease",
    "epilepsy",
    "glaucoma",
    "cataract",
    "anemia",
    "hemophilia",
    "lupus",
    "celiac disease",
    "gout",
    "GERD",
    "IBS",
    "pancreatitis",
  ],
  enMedicalSpecialties: [
    "Cardiology", // قلب
    "Neurology", // مغز و اعصاب
    "Oncology", // سرطان‌شناسی
    "Orthopedics", // ارتوپدی (استخوان و مفاصل)
    "Pediatrics", // کودکان
    "Internal Medicine", // داخلی
    "General Surgery", // جراحی عمومی
    "Neurosurgery", // جراحی مغز و اعصاب
    "Plastic Surgery", // جراحی پلاستیک
    "Psychiatry", // روان‌پزشکی
    "Endocrinology", // غدد
    "Gastroenterology", // گوارش
    "Dermatology", // پوست
    "Nephrology", // کلیه
    "Pulmonology", // ریه
    "Urology", // مجاری ادراری
    "Ophthalmology", // چشم‌پزشکی
    "Otolaryngology", // گوش، حلق و بینی (ENT)
    "Hematology", // خون‌شناسی
    "Rheumatology", // روماتولوژی (بیماری‌های مفصلی)
    "Infectious Diseases", // بیماری‌های عفونی
    "Obstetrics", // زایمان
    "Gynecology", // زنان
    "Anesthesiology", // بیهوشی
    "Pathology", // آسیب‌شناسی
    "Radiology", // تصویربرداری
    "Nuclear Medicine", // پزشکی هسته‌ای
    "Immunology", // ایمنی‌شناسی
    "Family Medicine", // پزشکی خانواده
    "Sports Medicine", // پزشکی ورزشی
    "Geriatrics", // سالمندان
    "Emergency Medicine", // اورژانس
    "Clinical Genetics", // ژنتیک بالینی
    "Forensic Medicine", // پزشکی قانونی
    "Occupational Medicine", // پزشکی کار
    "Allergy and Immunology", // آلرژی و ایمنی
    "Rehabilitation Medicine", // توانبخشی
    "Palliative Medicine", // مراقبت تسکینی
    "Sleep Medicine", // اختلالات خواب
    "Aerospace Medicine", // پزشکی هوافضا
  ],
  enReptiles: [
    //خزنده
    "Green Iguana",
    "Komodo Dragon",
    "Bearded Dragon",
    "Leopard Gecko",
    "Crested Gecko",
    "Tokay Gecko",
    "Day Gecko",
    "Chameleon",
    "Jackson's Chameleon",
    "Veiled Chameleon",
    "Monitor Lizard",
    "Savannah Monitor",
    "Nile Monitor",
    "Blue-tongued Skink",
    "Tegu",
    "Gila Monster",
    "Mexican Beaded Lizard",
    "Anole",
    "Basilisk Lizard",
    "Frilled Lizard",
    "Horned Lizard",
    "Glass Lizard",
    "Alligator",
    "Crocodile",
    "Caiman",
    "Gharial",
    "Box Turtle",
    "Snapping Turtle",
    "Red-eared Slider",
    "Russian Tortoise",
    "Sulcata Tortoise",
    "Leopard Tortoise",
    "King Cobra",
    "Ball Python",
    "Corn Snake",
    "Boa Constrictor",
    "Reticulated Python",
    "Garter Snake",
    "Rattlesnake",
    "Milk Snake",
    "Copperhead",
    "Water Moccasin",
    "Green Tree Python",
    "Black Mamba",
    "Inland Taipan",
    "Eastern Coral Snake",
    "Indian Cobra",
    "Sand Boa",
    "Burmese Python",
  ],
  enBirds: [
    "Sparrow",
    "Pigeon",
    "Crow",
    "Parrot",
    "Canary",
    "Finch",
    "Robin",
    "Swallow",
    "Kingfisher",
    "Hummingbird",
    "Peacock",
    "Ostrich",
    "Penguin",
    "Eagle",
    "Falcon",
    "Hawk",
    "Vulture",
    "Heron",
    "Stork",
    "Swan",
    "Duck",
    "Goose",
    "Flamingo",
    "Pelican",
    "Woodpecker",
    "Owl",
    "Nightjar",
    "Seagull",
    "Albatross",
    "Tern",
    "Toucan",
    "Macaw",
    "Cockatoo",
    "Lark",
    "Thrush",
    "Magpie",
    "Jay",
    "Raven",
    "Kite",
    "Quail",
    "Partridge",
    "Turkey",
    "Hen",
    "Rooster",
    "Pheasant",
    "Cuckoo",
    "Hornbill",
    "Bee-eater",
    "Hoopoe",
    "Wagtail",
    "Nightingale",
    "Bunting",
    "Goldfinch",
    "Waxwing",
    "Starling",
    "Warbler",
    "Shrike",
    "Swift",
    "Lorikeet",
    "Lyrebird",
  ],
  enMammals: [
    "Lion",
    "Tiger",
    "Leopard",
    "Jaguar",
    "Cheetah",
    "Panther",
    "Elephant",
    "Rhinoceros",
    "Hippopotamus",
    "Giraffe",
    "Zebra",
    "Horse",
    "Donkey",
    "Cow",
    "Bull",
    "Goat",
    "Sheep",
    "Pig",
    "Dog",
    "Cat",
    "Wolf",
    "Fox",
    "Bear",
    "Polar Bear",
    "Grizzly Bear",
    "Panda",
    "Koala",
    "Kangaroo",
    "Wallaby",
    "Camel",
    "Llama",
    "Alpaca",
    "Deer",
    "Moose",
    "Elk",
    "Reindeer",
    "Rabbit",
    "Hare",
    "Squirrel",
    "Rat",
    "Mouse",
    "Hedgehog",
    "Porcupine",
    "Beaver",
    "Otter",
    "Badger",
    "Skunk",
    "Raccoon",
    "Wombat",
    "Sloth",
    "Armadillo",
    "Opossum",
    "Chimpanzee",
    "Gorilla",
    "Orangutan",
    "Baboon",
    "Monkey",
    "Bat",
    "Whale",
    "Dolphin",
    "Porpoise",
    "Seal",
    "Walrus",
    "Manatee",
    "Antelope",
    "Bison",
    "Yak",
    "Mole",
    "Shrew",
    "Lemur",
    "Meerkat",
  ],
  enAmphibians: [
    "Axolotl",
    "Fire Salamander",
    "Golden Toad",
    "Green Tree Frog",
    "Hellbender",
    "Luristan Newt",
    "Poison Dart Frog",
    "Red‑Eyed Tree Frog",
    "African Bullfrog",
    "African Clawed Frog",
    "African Tree Toad",
    "American Toad",
    "Argentine Horned Frog",
    "Bullfrog",
    "Burrowing Frog",
    "Common Frog",
    "Darwin’s Frog",
    "Desert Rain Frog",
    "Edible Frog",
    "Glass Frog",
    "Goliath Frog",
    "Gray Tree Frog",
    "Green Frog",
    "Marsh Frog",
    "Common Toad",
    "Natterjack Toad",
    "Smooth Newt",
    "Great Crested Newt",
    "Palate Newt",
    "Egyptian Toad",
    "Eastern Spadefoot Toad",
    "Caucasian Toad",
    "European Fire‑Belly Toad",
    "Yellow‑Bellied Toad",
    "Oriental Fire‑Belly Toad",
    "Spanish Painted Frog",
    "Painted Frog",
    "Common Tree Frog",
    "Oriental Tree Frog",
    "Italian Agile Frog",
    "Moor Frog",
    "Marsh Frog",
    "Pool Frog",
    "Edible Frog (Pelophylax esculentus)",
    "American Bullfrog",
    "Northern Crested Newt",
    "Southern Crested Newt",
    "Smooth Newt",
    "Italian Stream Frog",
    "African Foam‑Nest Tree Frog",
    "Yellow‑Striped Caecilian",
    "Taita African Caecilian",
    "Mexican Burrowing Caecilian",
    "Rain Frog",
    "Pacific Giant Salamander",
    "Common Mudpuppy",
    "Texas Blind Salamander",
    "Blanco Blind Salamander",
    "Barton Springs Salamander",
    "African Foam‑Nest Frog",
    "Common Splayfoot Salamander",
    "Bigfoot Splayfoot Salamander",
    "Primeval Splayfoot Salamander",
    "Hidden Tree Frog",
    "Mientien Tree Frog",
    "Sheep Frog",
    "Mount Lyell Salamander",
    "Japanese Clawed Salamander",
    "Korean Crevice Salamander",
    "African Clawed Frog",
    "Desert Rain Frog",
    "Red‑Eyed Tree Frog",
    "Fire‑Bellied Toad",
    "Giant Salamander",
    "Glass Frog",
    "Green Tree Frog",
    "Marsh Frog",
    "Bullfrog",
    "African Bullfrog",
    "American Toad",
    "Common Toad",
  ],
  enInsects: [
    "Ant",
    "Bee",
    "Wasp",
    "Hornet",
    "Butterfly",
    "Moth",
    "Dragonfly",
    "Damselfly",
    "Grasshopper",
    "Cricket",
    "Katydid",
    "Locust",
    "Beetle",
    "Ladybug",
    "Firefly",
    "Weevil",
    "Stag-Beetle",
    "Rhinoceros-Beetle",
    "Leaf-Beetle",
    "June-Bug",
    "Click-Beetle",
    "Dung-Beetle",
    "Flea",
    "Louse",
    "Aphid",
    "Cicada",
    "Shield-Bug",
    "Stink-Bug",
    "Bed-Bug",
    "Assassin-Bug",
    "Mosquito",
    "Gnat",
    "Fly",
    "House-Fly",
    "Fruit-Fly",
    "Horse-Fly",
    "Deer-Fly",
    "Bot-Fly",
    "Blow-Fly",
    "Mayfly",
    "Stonefly",
    "Dobsonfly",
    "Lacewing",
    "Antlion",
    "Mantid",
    "Praying-Mantis",
    "Stick-Insect",
    "Leaf-Insect",
    "Termite",
    "Silverfish",
    "Springtail",
    "Thrips",
    "Earwig",
    "Booklouse",
    "Bark-Louse",
    "Caddisfly",
    "Sawfly",
    "Ichneumon-Wasp",
    "Velvet-Ant",
    "Carpenter-Bee",
    "Leafcutter-Bee",
    "Sweat-Bee",
    "Hoverfly",
    "Gall-Midge",
    "Tiger-Beetle",
    "Ground-Beetle",
    "Water-Beetle",
    "Water-Strider",
    "Backswimmer",
    "Water-Boatman",
    "Bumblebee",
    "Paper-Wasp",
    "Ensign-Wasp",
  ],
  enPlants: [
    "Aloe-Vera",
    "Basil",
    "Rosemary",
    "Lavender",
    "Thyme",
    "Oregano",
    "Parsley",
    "Mint",
    "Cilantro",
    "Dill",
    "Sage",
    "Chives",
    "Lemongrass",
    "Bay-Leaf",
    "Chamomile",
    "Echinacea",
    "Ginger",
    "Turmeric",
    "Garlic",
    "Onion",
    "Tomato",
    "Potato",
    "Carrot",
    "Spinach",
    "Lettuce",
    "Cabbage",
    "Broccoli",
    "Cauliflower",
    "Peas",
    "Beans",
    "Corn",
    "Wheat",
    "Barley",
    "Rice",
    "Sugarcane",
    "Sunflower",
    "Pumpkin",
    "Cucumber",
    "Watermelon",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Apple-Tree",
    "Peach-Tree",
    "Orange-Tree",
    "Lemon-Tree",
    "Banana-Plant",
    "Date-Palm",
    "Coconut-Palm",
    "Olive-Tree",
    "Fig-Tree",
    "Pine-Tree",
    "Fir-Tree",
    "Cedar-Tree",
    "Birch-Tree",
    "Maple-Tree",
    "Oak-Tree",
    "Willow-Tree",
    "Bamboo",
    "Fern",
    "Cactus",
    "Succulent",
    "Ivy",
    "Pothos",
    "Snake-Plant",
    "Spider-Plant",
    "Peace-Lily",
    "ZZ-Plant",
    "Fiddle-Leaf-Fig",
    "Philodendron",
    "Monstera",
    "Orchid",
  ],
  enInvertebrates: [
    //بی مهرگان
    "Earthworm",
    "Leech",
    "Snail",
    "Slug",
    "Octopus",
    "Squid",
    "Cuttlefish",
    "Jellyfish",
    "Sea Anemone",
    "Coral",
    "Sea Urchin",
    "Starfish",
    "Sand Dollar",
    "Crab",
    "Lobster",
    "Shrimp",
    "Barnacle",
    "Copepod",
    "Krill",
    "Tick",
    "Mite",
    "Spider",
    "Scorpion",
    "Horseshoe Crab",
    "Centipede",
    "Millipede",
    "Cockroach",
    "Ant",
    "Bee",
    "Wasp",
    "Butterfly",
    "Moth",
    "Dragonfly",
    "Damselfly",
    "Grasshopper",
    "Cricket",
    "Flea",
    "Louse",
    "Aphid",
    "Cicada",
    "Silverfish",
    "Termite",
    "Velvet Worm",
    "Ribbon Worm",
    "Flatworm",
    "Tapeworm",
    "Planarian",
    "Sea Slug",
    "Nudibranch",
    "Hydra",
    "Sponges",
    "Comb Jelly",
    "Arrow Worm",
    "Brachiopod",
    "Bryozoan",
    "Rotifer",
    "Tardigrade",
    "Sea Sponge",
    "Glass Sponge",
    "Clam",
    "Oyster",
    "Mussel",
    "Scallop",
    "Cockle",
    "Chiton",
    "Sea Cucumber",
    "Feather Star",
    "Crinoid",
  ],
  enFlowers: [
    "Rose",
    "Tulip",
    "Lily",
    "Daffodil",
    "Sunflower",
    "Orchid",
    "Marigold",
    "Chrysanthemum",
    "Daisy",
    "Carnation",
    "Peony",
    "Hydrangea",
    "Azalea",
    "Begonia",
    "Camellia",
    "Crocus",
    "Dahlia",
    "Freesia",
    "Gardenia",
    "Geranium",
    "Gladiolus",
    "Hibiscus",
    "Iris",
    "Jasmine",
    "Lavender",
    "Lilac",
    "Magnolia",
    "Narcissus",
    "Pansy",
    "Petunia",
    "Phlox",
    "Plumeria",
    "Ranunculus",
    "Snapdragon",
    "Stock",
    "Sweet-Pea",
    "Violet",
    "Zinnia",
    "Bluebell",
    "Buttercup",
    "Calla-Lily",
    "Clematis",
    "Coneflower",
    "Cosmos",
    "Cyclamen",
    "Fuchsia",
    "Gardenia",
    "Hellebore",
    "Heliotrope",
    "Honeysuckle",
    "Impatiens",
    "Kalanchoe",
    "Lantana",
    "Lobelia",
    "Monkshood",
    "Morning-Glory",
    "Oleander",
    "Passion-Flower",
    "Peach-Blossom",
    "Queen-Anne’s-Lace",
    "Ranunculus",
    "Redbud",
    "Salvia",
    "Scabiosa",
    "Stock",
    "Sweet William",
    "Tuberose",
    "Wallflower",
    "Yarrow",
  ],
  enCompanies: [
    "Apple",
    "Microsoft",
    "Amazon",
    "Alphabet (Google)",
    "Facebook (Meta)",
    "Tesla",
    "Samsung",
    "IBM",
    "Intel",
    "Cisco",
    "Oracle",
    "NVIDIA",
    "Sony",
    "Toyota",
    "Volkswagen",
    "General Motors",
    "Ford",
    "Honda",
    "BMW",
    "Mercedes-Benz",
    "Johnson & Johnson",
    "Pfizer",
    "Novartis",
    "Roche",
    "Procter & Gamble",
    "Unilever",
    "Coca-Cola",
    "PepsiCo",
    "Nestlé",
    "Walmart",
    "Alibaba",
    "Tencent",
    "Berkshire Hathaway",
    "JPMorgan Chase",
    "Goldman Sachs",
    "Visa",
    "Mastercard",
    "ExxonMobil",
    "Chevron",
    "Shell",
  ],
  enContries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of the",
    "Congo, Republic of the",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
  enApps: [
    "Microsoft Windows",
    "macOS",
    "Linux (Kernel and Distributions)",
    "Microsoft Office Suite",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "AutoCAD",
    "Google Chrome",
    "Mozilla Firefox",
    "Safari",
    "Oracle Database",
    "MySQL",
    "PostgreSQL",
    "Microsoft SQL Server",
    "SAP ERP",
    "Salesforce",
    "Slack",
    "Zoom",
    "Skype",
    "Dropbox",
    "Git",
    "Visual Studio",
    "IntelliJ IDEA",
    "Eclipse",
    "Android Studio",
    "Xcode",
    "Blender",
    "3ds Max",
    "Maya",
    "Unity",
    "Unreal Engine",
    "MATLAB",
    "RStudio",
    "Tableau",
    "Power BI",
    "Kali Linux",
    "Nmap",
    "Wireshark",
    "Docker",
    "Kubernetes",
    "TensorFlow",
    "PyTorch",
    "Jira",
    "Confluence",
    "WordPress",
    "Magento",
    "Google Analytics",
    "Trello",
    "Notepad++",
    "Vim",
  ],
  enAlphabets: [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ],
  enHandiTools: [
    "Adjustable Wrench",
    "Pliers",
    "Needle-nose Pliers",
    "Hammer",
    "Screwdriver",
    "Flathead Screwdriver",
    "Phillips Screwdriver",
    "Tape Measure",
    "Utility Knife",
    "Handsaw",
    "Chisel",
    "Level",
    "Wire Stripper",
    "Allen Wrench (Hex Key)",
    "C-Clamp",
    "Pipe Wrench",
    "Hacksaw",
    "Crowbar",
    "Putty Knife",
    "Rasp",
    "Hand Drill",
    "Socket Wrench",
    "Combination Square",
    "Spade Bit",
    "Speed Square",
    "Mallet",
    "Clamp",
    "Wire Brush",
    "Wire Cutter",
    "Bolt Cutter",
    "Caulking Gun",
    "Trowel",
    "Scraper",
    "Nail Puller",
    "Tap and Die Set",
    "Leveling Tool",
    "Pry Bar",
    "Wire Crimper",
    "Punch",
    "Feeler Gauge",
    "Spanner",
    "Brace",
    "Hand Plane",
    "Tin Snips",
    "Pipe Cutter",
    "Deburring Tool",
    "Chalk Line",
    "Plumb Bob",
    "Hole Saw",
    "Ratchet",
  ],
  enKitchenTools: [
    "Knife",
    "Cutting Board",
    "Peeler",
    "Whisk",
    "Spatula",
    "Measuring Cup",
    "Measuring Spoon",
    "Mixing Bowl",
    "Colander",
    "Grater",
    "Can Opener",
    "Blender",
    "Food Processor",
    "Microwave",
    "Oven",
    "Stove",
    "Saucepan",
    "Frying Pan",
    "Pot",
    "Kettle",
    "Toaster",
    "Coffee Maker",
    "Rice Cooker",
    "Slow Cooker",
    "Pressure Cooker",
    "Rolling Pin",
    "Tongs",
    "Ladle",
    "Sieve",
    "Thermometer",
    "Timer",
    "Mandoline",
    "Kitchen Shears",
    "Garlic Press",
    "Baking Tray",
    "Cooling Rack",
    "Mortar and Pestle",
    "Meat Tenderizer",
    "Salad Spinner",
    "Electric Mixer",
    "Chopping Knife",
    "Bread Knife",
    "Spoon",
    "Fork",
    "Forklift",
    "Serving Spoon",
    "Funnel",
    "Dish Rack",
    "Ice Cream Scoop",
    "Kitchen Scale",
  ],
  enCars: [
    "Toyota Corolla",
    "Honda Civic",
    "Ford Mustang",
    "Chevrolet Camaro",
    "BMW 3 Series",
    "Mercedes-Benz C-Class",
    "Audi A4",
    "Tesla Model S",
    "Nissan Altima",
    "Volkswagen Golf",
    "Hyundai Elantra",
    "Kia Optima",
    "Subaru Outback",
    "Mazda CX-5",
    "Jeep Wrangler",
    "Dodge Charger",
    "Lexus RX",
    "Volvo XC90",
    "Porsche 911",
    "Ferrari F8",
    "Lamborghini Huracan",
    "Maserati Ghibli",
    "Bentley Continental",
    "Rolls-Royce Phantom",
    "Bugatti Chiron",
    "Chevrolet Silverado",
    "Ford F-150",
    "Ram 1500",
    "GMC Sierra",
    "Honda CR-V",
    "Toyota RAV4",
    "Tesla Model 3",
    "Audi Q5",
    "Mercedes-Benz G-Class",
    "BMW X5",
    "Land Rover Range Rover",
    "Jaguar F-Type",
    "Alfa Romeo Giulia",
    "Acura MDX",
    "Infiniti Q50",
    "Lincoln Navigator",
    "Cadillac Escalade",
    "Mini Cooper",
    "Fiat 500",
    "Smart Fortwo",
    "Subaru Impreza",
    "Toyota Prius",
    "Nissan GT-R",
    "Ford Explorer",
    "Chevrolet Tahoe",
    "Hyundai Santa Fe",
    "Kia Sorento",
    "Volkswagen Passat",
    "Mazda MX-5 Miata",
    "Tesla Model X",
    "Audi R8",
    "Mercedes-Benz E-Class",
    "BMW M3",
    "Honda Accord",
    "Toyota Camry",
    "Jeep Grand Cherokee",
    "Land Rover Discovery",
    "Dodge Durango",
    "Ford Escape",
    "Chevrolet Equinox",
    "Subaru Forester",
    "Nissan Rogue",
    "Volkswagen Tiguan",
    "Hyundai Tucson",
    "Kia Sportage",
    "Mazda CX-3",
    "Tesla Model Y",
    "Audi Q7",
    "Mercedes-Benz S-Class",
    "BMW 7 Series",
    "Cadillac CTS",
    "Lexus ES",
    "Acura TLX",
    "Infiniti QX60",
    "Jaguar XE",
    "Lincoln Continental",
  ],
  enClothes: [
    "T-shirt",
    "Shirt",
    "Blouse",
    "Sweater",
    "Hoodie",
    "Jacket",
    "Coat",
    "Vest",
    "Jeans",
    "Trousers",
    "Shorts",
    "Skirt",
    "Dress",
    "Suit",
    "Tie",
    "Scarf",
    "Gloves",
    "Hat",
    "Cap",
    "Beanie",
    "Socks",
    "Stockings",
    "Leggings",
    "Sweatpants",
    "Pyjamas",
    "Bathrobe",
    "Swimsuit",
    "Bikini",
    "Overalls",
    "Cardigan",
    "Polo Shirt",
    "Denim Jacket",
    "Leather Jacket",
    "Windbreaker",
    "Raincoat",
    "Blazer",
    "Tracksuit",
    "Tuxedo",
    "Camisole",
    "Tank Top",
    "Button-up Shirt",
    "Dungarees",
    "Peacoat",
    "Poncho",
    "Kimono",
    "Sarong",
    "Shawl",
    "Wrap Dress",
    "Maxi Dress",
    "Midi Dress",
    "Crop Top",
    "Cargo Pants",
    "Chinos",
    "Culottes",
    "Flannel Shirt",
    "Harem Pants",
    "Jumpsuit",
    "Kaftan",
    "Leg Warmers",
    "Mittens",
    "Necklace",
    "Earrings",
    "Bracelet",
    "Watch",
    "Belt",
    "Suspenders",
    "Bow Tie",
    "Turtleneck",
    "Trench Coat",
    "Uniform",
    "Vest Dress",
    "Wedding Dress",
    "Evening Gown",
    "Tracksuit Bottoms",
    "Yoga Pants",
    "Zipper Hoodie",
    "Graphic Tee",
  ],
  enTreeNames: [
    "Oak",
    "Pine",
    "Maple",
    "Birch",
    "Cedar",
    "Spruce",
    "Fir",
    "Willow",
    "Ash",
    "Beech",
    "Cherry",
    "Chestnut",
    "Cottonwood",
    "Dogwood",
    "Elm",
    "Hemlock",
    "Hickory",
    "Larch",
    "Magnolia",
    "Maple-Leaf Oak",
    "Mulberry",
    "Palm",
    "Poplar",
    "Redwood",
    "Sequoia",
    "Sycamore",
    "Tamarack",
    "Walnut",
    "Yew",
    "Alder",
    "Aspen",
    "Bald Cypress",
    "Black Locust",
    "Black Walnut",
    "Boxwood",
    "Cypress",
    "Eucalyptus",
    "Ginkgo",
    "Hazel",
    "Holly",
    "Ironwood",
    "Juniper",
    "Kapok",
    "Linden",
    "Mahogany",
    "Mimosa",
    "Mulberry",
    "Olive",
    "Osage Orange",
    "Pecan",
    "Persimmon",
    "Plane Tree",
    "Ponderosa Pine",
    "Red Maple",
    "Sassafras",
    "Serviceberry",
    "Sweetgum",
    "Tupelo",
    "Tulip Tree",
    "White Oak",
    "Yellow Poplar",
    "Zelkova",
    "Bristlecone Pine",
    "Catalpa",
    "Chinkapin Oak",
    "Coast Redwood",
    "Cork Oak",
    "Douglas Fir",
    "Fraser Fir",
    "Giant Sequoia",
    "Kentucky Coffeetree",
    "Loblolly Pine",
    "Monterey Pine",
    "Norway Spruce",
    "Paper Birch",
    "Ponderosa Pine",
    "Red Pine",
    "Scarlet Oak",
  ],
  enInventor: [
    "Thomas Edison",
    "Nikola Tesla",
    "Alexander Graham Bell",
    "Leonardo da Vinci",
    "Galileo Galilei",
    "James Watt",
    "Benjamin Franklin",
    "Marie Curie",
    "Michael Faraday",
    "Wright Brothers",
    "Samuel Morse",
    "Guglielmo Marconi",
    "Isaac Newton",
    "Archimedes",
    "Johannes Gutenberg",
    "Louis Pasteur",
    "George Washington Carver",
    "Eli Whitney",
    "Henry Ford",
    "Alessandro Volta",
    "Charles Babbage",
    "Richard Trevithick",
    "Robert Fulton",
    "Tim Berners-Lee",
    "John Logie Baird",
    "Philo Farnsworth",
    "Elisha Otis",
    "Nikolaus Otto",
    "Rudolf Diesel",
    "Edwin Land",
    "Hedy Lamarr",
    "Karl Benz",
    "Otto Lilienthal",
    "James Dyson",
    "Sergey Korolev",
    "Grace Hopper",
    "Charles Goodyear",
    "Gottlieb Daimler",
    "Alexander Fleming",
    "Wilbur Wright",
    "Orville Wright",
    "Dennis Ritchie",
    "Steve Jobs",
    "Bill Gates",
    "Alan Turing",
    "Jonas Salk",
    "Robert Noyce",
    "John Bardeen",
    "Walter Brattain",
    "William Shockley",
    "Igor Sikorsky",
    "Leonardo Torres Quevedo",
    "Alfred Nobel",
    "Samuel Colt",
    "James Clerk Maxwell",
    "Alexander Parkes",
    "Josephine Cochrane",
    "Louis Braille",
    "Edwin Armstrong",
    "George Eastman",
    "Nikola Tesla",
    "George Stephenson",
    "John Kay",
    "Ada Lovelace",
    "Emile Berliner",
    "Nikola Tesla",
    "Philo Farnsworth",
    "Robert Goddard",
    "Francis Crick",
    "James Watson",
    "Marie Curie",
    "Richard Feynman",
    "Guglielmo Marconi",
    "Leonardo da Vinci",
    "Thomas Newcomen",
    "Alessandro Volta",
    "Antoine Lavoisier",
    "Hiram Maxim",
    "Samuel Morse",
    "George Westinghouse",
  ],
  enPhilosopher: [
    "Socrates",
    "Plato",
    "Aristotle",
    "Confucius",
    "Immanuel Kant",
    "Friedrich Nietzsche",
    "John Locke",
    "René Descartes",
    "David Hume",
    "Thomas Aquinas",
    "Baruch Spinoza",
    "Jean-Jacques Rousseau",
    "Karl Marx",
    "Georg Wilhelm Friedrich Hegel",
    "Ludwig Wittgenstein",
    "Simone de Beauvoir",
    "Michel Foucault",
    "Albert Camus",
    "Søren Kierkegaard",
    "Martin Heidegger",
    "Epicurus",
    "Zeno of Citium",
    "Augustine of Hippo",
    "Blaise Pascal",
    "Bertrand Russell",
    "Francis Bacon",
    "John Stuart Mill",
    "Hannah Arendt",
    "G.W.F. Hegel",
    "Plotinus",
    "Al-Farabi",
    "Avicenna",
    "Averroes",
    "Thomas Hobbes",
    "Jean-Paul Sartre",
    "Baruch Spinoza",
    "David Ricardo",
    "Francisco Suárez",
    "Ralph Waldo Emerson",
    "Friedrich Engels",
    "Heraclitus",
    "Parmenides",
    "Giordano Bruno",
    "Emmanuel Levinas",
    "George Berkeley",
    "Arthur Schopenhauer",
    "John Dewey",
    "Alain Badiou",
    "Gilles Deleuze",
    "Judith Butler",
    "Mary Wollstonecraft",
    "Thomas Nagel",
    "Ayn Rand",
    "Noam Chomsky",
    "Cornel West",
    "Richard Rorty",
    "Jürgen Habermas",
    "Slavoj Žižek",
    "Peter Singer",
    "Michel de Montaigne",
    "Marcus Aurelius",
    "Diogenes",
    "Democritus",
    "Anaximander",
    "Protagoras",
    "Epicurus",
    "Seneca",
    "Cicero",
    "Thomas More",
    "G.E. Moore",
    "Alfred North Whitehead",
    "Hermann Cohen",
    "Max Scheler",
    "Wilhelm Dilthey",
    "Hans-Georg Gadamer",
    "Karl Popper",
    "Isaiah Berlin",
    "H.L.A. Hart",
  ],
  enAcademicMajor: [
    "Computer Science",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Business Administration",
    "Economics",
    "Psychology",
    "Biology",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Architecture",
    "Political Science",
    "Sociology",
    "History",
    "Philosophy",
    "Law",
    "Medicine",
    "Nursing",
    "Pharmacy",
    "Dentistry",
    "Veterinary Medicine",
    "Environmental Science",
    "Education",
    "Journalism",
    "Graphic Design",
    "Marketing",
    "Finance",
    "Accounting",
    "International Relations",
    "Anthropology",
    "Linguistics",
    "Music",
    "Fine Arts",
    "Theater Arts",
    "Film Studies",
    "Public Health",
    "Social Work",
    "Urban Planning",
    "Information Technology",
    "Data Science",
    "Artificial Intelligence",
    "Cybersecurity",
    "Biotechnology",
    "Geology",
    "Astronomy",
    "Mathematics Education",
    "Physical Education",
    "Nutrition",
    "Agriculture",
    "Forestry",
    "Hotel Management",
    "Tourism",
    "Sports Management",
    "Criminal Justice",
    "Human Resources",
    "Supply Chain Management",
    "Mechanical Engineering Technology",
    "Electrical Engineering Technology",
    "Civil Engineering Technology",
    "Business Analytics",
    "Media Studies",
    "Religious Studies",
    "Gender Studies",
    "Creative Writing",
    "Law Enforcement",
    "Actuarial Science",
    "Oceanography",
    "Nanotechnology",
    "Robotics",
    "Liberal Arts",
    "Cognitive Science",
    "Speech Pathology",
    "Veterinary Technology",
    "Real Estate",
    "Public Administration",
    "Film Production",
    "Dance",
    "Interior Design",
    "Advertising",
    "Event Management",
    "Journalism and Mass Communication",
  ],
  enSports: [
    "Soccer",
    "Basketball",
    "Tennis",
    "Baseball",
    "Volleyball",
    "Golf",
    "Cricket",
    "Rugby",
    "Ice Hockey",
    "Field Hockey",
    "Swimming",
    "Track and Field",
    "Gymnastics",
    "Boxing",
    "Wrestling",
    "Table Tennis",
    "Badminton",
    "Cycling",
    "Skiing",
    "Snowboarding",
    "Surfing",
    "Skateboarding",
    "Martial Arts",
    "Judo",
    "Karate",
    "Taekwondo",
    "Fencing",
    "Archery",
    "Shooting",
    "Weightlifting",
    "Powerlifting",
    "CrossFit",
    "Triathlon",
    "Rowing",
    "Kayaking",
    "Canoeing",
    "Horseback Riding",
    "Lacrosse",
    "Diving",
    "Curling",
    "Bobsledding",
    "Skeleton",
    "Speed Skating",
    "Figure Skating",
    "Synchronized Swimming",
    "Handball",
    "Softball",
    "Ultimate Frisbee",
    "Polo",
    "Squash",
    "Rock Climbing",
    "Parkour",
    "Kickboxing",
    "Muay Thai",
    "Capoeira",
    "Paintball",
    "Airsoft",
    "BMX",
    "Motocross",
    "Drag Racing",
    "Auto Racing",
    "Golf",
    "Snooker",
    "Darts",
    "Bowling",
    "Cheerleading",
    "Horse Racing",
    "Fishing",
    "Sailing",
    "Bodybuilding",
    "Paragliding",
    "Hang Gliding",
    "Skydiving",
    "Ballet",
    "Yoga",
    "Pilates",
    "Zumba",
    "Cross Country Skiing",
    "Snowshoeing",
  ],
  enClimbingGear: [
    "Backpack",
    "Climbing Harness",
    "Carabiner",
    "Climbing Rope",
    "Helmet",
    "Climbing Shoes",
    "Belay Device",
    "Ice Axe",
    "Crampons",
    "Trekking Poles",
    "Headlamp",
    "Gloves",
    "Tent",
    "Sleeping Bag",
    "Sleeping Pad",
    "Water Bottle",
    "Hydration System",
    "Map",
    "Compass",
    "GPS Device",
    "First Aid Kit",
    "Multi-tool",
    "Sunglasses",
    "Sunblock",
    "Climbing Chalk",
    "Ascender",
    "Descender",
    "Anchor",
    "Prusik Loop",
    "Climbing Tape",
    "Gaiters",
    "Snow Goggles",
    "Avalanche Beacon",
    "Avalanche Probe",
    "Avalanche Shovel",
    "Stove",
    "Fuel",
    "Cookware",
    "Food Supplies",
    "Emergency Blanket",
    "Whistle",
    "Portable Charger",
    "Extra Clothing",
    "Fleece Jacket",
    "Rain Jacket",
    "Base Layers",
    "Insulated Jacket",
    "Hat",
    "Neck Gaiter",
    "Waterproof Pants",
    "Climbing Helmet",
    "Bug Spray",
  ],
  enlanguage: [
    "English",
    "Mandarin Chinese",
    "Hindi",
    "Spanish",
    "French",
    "Arabic",
    "Bengali",
    "Russian",
    "Portuguese",
    "Urdu",
    "Indonesian",
    "German",
    "Japanese",
    "Swahili",
    "Marathi",
    "Telugu",
    "Turkish",
    "Tamil",
    "Western Punjabi",
    "Wu Chinese",
    "Korean",
    "Vietnamese",
    "Hausa",
    "Javanese",
    "Egyptian Arabic",
    "Italian",
    "Thai",
    "Gujarati",
    "Kannada",
    "Persian (Farsi)",
    "Bhojpuri",
    "Southern Min",
    "Hakka",
    "Jin Chinese",
    "Pashto",
    "Xiang Chinese",
    "Malayalam",
    "Sundanese",
    "Haryanvi",
    "Hungarian",
    "Odisha (Odia)",
    "Burmese",
    "Sanskrit",
    "Serbian",
    "Azerbaijani",
    "Czech",
    "Greek",
    "Dutch",
    "Kurdish",
    "Amharic",
    "Somali",
    "Belarusian",
    "Hebrew",
    "Swedish",
    "Bulgarian",
    "Danish",
    "Finnish",
    "Norwegian",
    "Slovak",
    "Croatian",
    "Lithuanian",
    "Latvian",
    "Estonian",
    "Macedonian",
    "Albanian",
    "Maltese",
    "Icelandic",
    "Irish",
    "Welsh",
    "Scottish Gaelic",
    "Basque",
    "Catalan",
    "Galician",
    "Luxembourgish",
    "Corsican",
    "Frisian",
    "Fijian",
    "Hawaiian",
    "Maori",
    "Samoan",
    "Tongan",
    "Tahitian",
    "Quechua",
    "Guarani",
    "Nahuatl",
    "Aymara",
    "Mapudungun",
    "Inuktitut",
    "Greenlandic",
    "Corsican",
  ],
  enStars: [
    "Sun",
    "Sirius",
    "Canopus",
    "Arcturus",
    "Alpha Centauri A",
    "Alpha Centauri B",
    "Proxima Centauri",
    "Vega",
    "Capella",
    "Rigel",
    "Betelgeuse",
    "Achernar",
    "Hadar",
    "Altair",
    "Aldebaran",
    "Spica",
    "Antares",
    "Pollux",
    "Fomalhaut",
    "Deneb",
    "Mimosa",
    "Regulus",
    "Adhara",
    "Castor",
    "Gacrux",
    "Bellatrix",
    "Elnath",
    "Miaplacidus",
    "Alnilam",
    "Alnair",
    "Alioth",
    "Dubhe",
    "Mirfak",
    "Wezen",
    "Sargas",
    "Kaus Australis",
    "Avior",
    "Alkaid",
    "Menkent",
    "Hamal",
    "Alphecca",
    "Polaris",
    "Schedar",
    "Alnitak",
    "Saiph",
    "Markab",
    "Alcor",
    "Mizar",
    "Alhena",
    "Rigil Kentaurus",
    "Atria",
    "Diphda",
    "Algol",
    "Caph",
    "Menkib",
    "Denebola",
    "Zubenelgenubi",
    "Zubeneschamali",
    "Rasalhague",
    "Alsephina",
    "Eltanin",
    "Ankaa",
    "Alphard",
    "Ruchbah",
    "Izar",
    "Muscida",
    "Cursa",
    "Aludra",
    "Sabik",
    "Suhail",
    "Alkaid",
    "Alphirk",
    "Maasym",
    "Kochab",
    "Saiph",
    "Algol",
    "Mirzam",
    "Sualocin",
    "Rotanev",
    "Gienah",
    "Nashira",
    "Tarazed",
    "Alrai",
    "Alphecca",
    "Eltanin",
    "Marfik",
    "Nunki",
    "Deneb Algedi",
    "Nashira",
    "Markeb",
    "Zaurak",
    "Almach",
  ],
  enChemicalElements: [
    "Hydrogen",
    "Helium",
    "Lithium",
    "Beryllium",
    "Boron",
    "Carbon",
    "Nitrogen",
    "Oxygen",
    "Fluorine",
    "Neon",
    "Sodium",
    "Magnesium",
    "Aluminum",
    "Silicon",
    "Phosphorus",
    "Sulfur",
    "Chlorine",
    "Argon",
    "Potassium",
    "Calcium",
    "Scandium",
    "Titanium",
    "Vanadium",
    "Chromium",
    "Manganese",
    "Iron",
    "Cobalt",
    "Nickel",
    "Copper",
    "Zinc",
    "Gallium",
    "Germanium",
    "Arsenic",
    "Selenium",
    "Bromine",
    "Krypton",
    "Rubidium",
    "Strontium",
    "Yttrium",
    "Zirconium",
    "Niobium",
    "Molybdenum",
    "Technetium",
    "Ruthenium",
    "Rhodium",
    "Palladium",
    "Silver",
    "Cadmium",
    "Indium",
    "Tin",
    "Antimony",
    "Tellurium",
    "Iodine",
    "Xenon",
    "Cesium",
    "Barium",
    "Lanthanum",
    "Cerium",
    "Praseodymium",
    "Neodymium",
    "Promethium",
    "Samarium",
    "Europium",
    "Gadolinium",
    "Terbium",
    "Dysprosium",
    "Holmium",
    "Erbium",
    "Thulium",
    "Ytterbium",
    "Lutetium",
    "Hafnium",
    "Tantalum",
    "Tungsten",
    "Rhenium",
    "Osmium",
    "Iridium",
    "Platinum",
    "Gold",
    "Mercury",
  ],
  enHumanOrgans: [
    "Brain",
    "Heart",
    "Lungs",
    "Liver",
    "Kidneys",
    "Stomach",
    "Intestines",
    "Pancreas",
    "Spleen",
    "Bladder",
    "Esophagus",
    "Gallbladder",
    "Thyroid gland",
    "Skin",
    "Muscles",
    "Bones",
    "Nervous System",
    "Circulatory System",
    "Respiratory System",
    "Digestive System",
    "Urinary System",
    "Endocrine System",
    "Reproductive System",
    "Skeletal System",
    "Muscular System",
    "Immune System",
    "Lymphatic System",
    "Eyes",
    "Ears",
    "Nose",
    "Mouth",
    "Teeth",
    "Tongue",
    "Hair",
    "Nails",
    "Spine",
    "Adrenal glands",
    "Thymus",
    "Appendix",
    "Large intestine",
    "Small intestine",
  ],
  enSeasAndLakes: [
    // دریاها
    "Mediterranean Sea",
    "Caribbean Sea",
    "Red Sea",
    "Black Sea",
    "Baltic Sea",
    "Arabian Sea",
    "South China Sea",
    "East China Sea",
    "Coral Sea",
    "Bering Sea",
    "Tasman Sea",
    "Adriatic Sea",
    "Aegean Sea",
    "Andaman Sea",
    "Celebes Sea",
    "Java Sea",
    "Okhotsk Sea",
    "Weddell Sea",
    "Scotia Sea",
    "Sargasso Sea",
    // دریاچه‌ها
    "Caspian Sea", // بزرگ‌ترین دریاچه جهان
    "Lake Superior",
    "Lake Victoria",
    "Lake Huron",
    "Lake Michigan",
    "Lake Tanganyika",
    "Lake Baikal",
    "Great Bear Lake",
    "Great Slave Lake",
    "Lake Malawi",
    "Lake Erie",
    "Lake Ontario",
    "Lake Winnipeg",
    "Lake Turkana",
    "Lake Chad",
    "Aral Sea",
    "Dead Sea",
    "Great Salt Lake",
  ],
  enNumbers: [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
    59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
    78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
    97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
    113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
    128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
    143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
    158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
    173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
    188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
    203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
    218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
    233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
    248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262,
    263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
    278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,
    293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307,
    308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322,
    323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
    338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
    353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367,
    368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382,
    383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397,
    398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
    413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427,
    428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442,
    443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457,
    458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472,
    473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487,
    488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502,
    503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
    518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
    533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547,
    548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562,
    563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577,
    578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592,
    593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607,
    608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622,
    623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637,
    638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652,
    653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667,
    668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682,
    683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697,
    698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712,
    713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
    728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742,
    743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757,
    758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772,
    773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787,
    788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802,
    803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817,
    818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832,
    833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847,
    848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862,
    863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877,
    878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892,
    893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907,
    908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
    923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937,
    938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952,
    953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967,
    968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982,
    983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997,
    998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
    1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
    1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
    1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046,
    1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058,
    1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070,
    1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082,
    1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094,
    1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106,
    1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118,
    1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130,
    1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142,
    1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154,
    1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166,
    1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178,
    1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190,
    1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202,
    1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214,
    1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226,
    1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238,
    1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250,
    1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262,
    1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274,
    1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286,
    1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298,
    1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310,
    1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322,
    1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334,
    1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346,
    1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358,
    1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370,
    1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382,
    1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394,
    1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406,
    1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418,
    1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430,
    1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442,
    1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454,
    1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466,
    1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478,
    1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490,
    1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502,
    1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514,
    1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526,
    1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538,
    1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550,
    1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562,
    1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574,
    1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586,
    1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598,
    1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610,
    1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622,
    1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634,
    1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646,
    1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658,
    1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670,
    1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682,
    1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694,
    1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706,
    1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718,
    1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730,
    1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742,
    1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754,
    1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766,
    1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778,
    1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790,
    1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802,
    1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814,
    1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826,
    1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838,
    1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850,
    1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862,
    1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874,
    1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886,
    1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898,
    1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
    1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922,
    1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934,
    1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
    1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958,
    1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
    1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
    1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
    1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
    2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
    2019, 2020, 2021, 2022, 2023, 2024, 2025,
  ],
  enNumbersInWords: [
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
    "twenty-one",
    "twenty-two",
    "twenty-three",
    "twenty-four",
    "twenty-five",
    "twenty-six",
    "twenty-seven",
    "twenty-eight",
    "twenty-nine",
    "thirty",
    "thirty-one",
    "thirty-two",
    "thirty-three",
    "thirty-four",
    "thirty-five",
    "thirty-six",
    "thirty-seven",
    "thirty-eight",
    "thirty-nine",
    "forty",
    "forty-one",
    "forty-two",
    "forty-three",
    "forty-four",
    "forty-five",
    "forty-six",
    "forty-seven",
    "forty-eight",
    "forty-nine",
    "fifty",
    "fifty-one",
    "fifty-two",
    "fifty-three",
    "fifty-four",
    "fifty-five",
    "fifty-six",
    "fifty-seven",
    "fifty-eight",
    "fifty-nine",
    "sixty",
    "sixty-one",
    "sixty-two",
    "sixty-three",
    "sixty-four",
    "sixty-five",
    "sixty-six",
    "sixty-seven",
    "sixty-eight",
    "sixty-nine",
    "seventy",
    "seventy-one",
    "seventy-two",
    "seventy-three",
    "seventy-four",
    "seventy-five",
    "seventy-six",
    "seventy-seven",
    "seventy-eight",
    "seventy-nine",
    "eighty",
    "eighty-one",
    "eighty-two",
    "eighty-three",
    "eighty-four",
    "eighty-five",
    "eighty-six",
    "eighty-seven",
    "eighty-eight",
    "eighty-nine",
    "ninety",
    "ninety-one",
    "ninety-two",
    "ninety-three",
    "ninety-four",
    "ninety-five",
    "ninety-six",
    "ninety-seven",
    "ninety-eight",
    "ninety-nine",
    "one-hundred",
    "one-hundred-one",
    "one-hundred-two",
    "one-hundred-three",
    "one-hundred-four",
    "one-hundred-five",
    "one-hundred-six",
    "one-hundred-seven",
    "one-hundred-eight",
    "one-hundred-nine",
    "one-hundred-ten",
    "one-hundred-eleven",
    "one-hundred-twelve",
    "one-hundred-thirteen",
    "one-hundred-fourteen",
    "one-hundred-fifteen",
    "one-hundred-sixteen",
    "one-hundred-seventeen",
    "one-hundred-eighteen",
    "one-hundred-nineteen",
    "one-hundred-twenty",
    "one-hundred-twenty-one",
    "one-hundred-twenty-two",
    "one-hundred-twenty-three",
    "one-hundred-twenty-four",
    "one-hundred-twenty-five",
    "one-hundred-twenty-six",
    "one-hundred-twenty-seven",
    "one-hundred-twenty-eight",
    "one-hundred-twenty-nine",
    "one-hundred-thirty",
    "one-hundred-thirty-one",
    "one-hundred-thirty-two",
    "one-hundred-thirty-three",
    "one-hundred-thirty-four",
    "one-hundred-thirty-five",
    "one-hundred-thirty-six",
    "one-hundred-thirty-seven",
    "one-hundred-thirty-eight",
    "one-hundred-thirty-nine",
    "one-hundred-forty",
    "one-hundred-forty-one",
    "one-hundred-forty-two",
    "one-hundred-forty-three",
    "one-hundred-forty-four",
    "one-hundred-forty-five",
    "one-hundred-forty-six",
    "one-hundred-forty-seven",
    "one-hundred-forty-eight",
    "one-hundred-forty-nine",
    "one-hundred-fifty",
    "one-hundred-fifty-one",
    "one-hundred-fifty-two",
    "one-hundred-fifty-three",
    "one-hundred-fifty-four",
    "one-hundred-fifty-five",
    "one-hundred-fifty-six",
    "one-hundred-fifty-seven",
    "one-hundred-fifty-eight",
    "one-hundred-fifty-nine",
    "one-hundred-sixty",
    "one-hundred-sixty-one",
    "one-hundred-sixty-two",
    "one-hundred-sixty-three",
    "one-hundred-sixty-four",
    "one-hundred-sixty-five",
    "one-hundred-sixty-six",
    "one-hundred-sixty-seven",
    "one-hundred-sixty-eight",
    "one-hundred-sixty-nine",
    "one-hundred-seventy",
    "one-hundred-seventy-one",
    "one-hundred-seventy-two",
    "one-hundred-seventy-three",
    "one-hundred-seventy-four",
    "one-hundred-seventy-five",
    "one-hundred-seventy-six",
    "one-hundred-seventy-seven",
    "one-hundred-seventy-eight",
    "one-hundred-seventy-nine",
    "one-hundred-eighty",
    "one-hundred-eighty-one",
    "one-hundred-eighty-two",
    "one-hundred-eighty-three",
    "one-hundred-eighty-four",
    "one-hundred-eighty-five",
    "one-hundred-eighty-six",
    "one-hundred-eighty-seven",
    "one-hundred-eighty-eight",
    "one-hundred-eighty-nine",
    "one-hundred-ninety",
    "one-hundred-ninety-one",
    "one-hundred-ninety-two",
    "one-hundred-ninety-three",
    "one-hundred-ninety-four",
    "one-hundred-ninety-five",
    "one-hundred-ninety-six",
    "one-hundred-ninety-seven",
    "one-hundred-ninety-eight",
    "one-hundred-ninety-nine",
    "two-hundred",
    "two-hundred-one",
    "two-hundred-two",
    "two-hundred-three",
    "two-hundred-four",
    "two-hundred-five",
    "two-hundred-six",
    "two-hundred-seven",
    "two-hundred-eight",
    "two-hundred-nine",
    "two-hundred-ten",
    "two-hundred-eleven",
    "two-hundred-twelve",
    "two-hundred-thirteen",
    "two-hundred-fourteen",
    "two-hundred-fifteen",
    "two-hundred-sixteen",
    "two-hundred-seventeen",
    "two-hundred-eighteen",
    "two-hundred-nineteen",
    "two-hundred-twenty",
    "two-hundred-twenty-one",
    "two-hundred-twenty-two",
    "two-hundred-twenty-three",
    "two-hundred-twenty-four",
    "two-hundred-twenty-five",
    "two-hundred-twenty-six",
    "two-hundred-twenty-seven",
    "two-hundred-twenty-eight",
    "two-hundred-twenty-nine",
    "two-hundred-thirty",
    "two-hundred-thirty-one",
    "two-hundred-thirty-two",
    "two-hundred-thirty-three",
    "two-hundred-thirty-four",
    "two-hundred-thirty-five",
    "two-hundred-thirty-six",
    "two-hundred-thirty-seven",
    "two-hundred-thirty-eight",
    "two-hundred-thirty-nine",
    "two-hundred-forty",
    "two-hundred-forty-one",
    "two-hundred-forty-two",
    "two-hundred-forty-three",
    "two-hundred-forty-four",
    "two-hundred-forty-five",
    "two-hundred-forty-six",
    "two-hundred-forty-seven",
    "two-hundred-forty-eight",
    "two-hundred-forty-nine",
    "two-hundred-fifty",
    "two-hundred-fifty-one",
    "two-hundred-fifty-two",
    "two-hundred-fifty-three",
    "two-hundred-fifty-four",
    "two-hundred-fifty-five",
    "two-hundred-fifty-six",
    "two-hundred-fifty-seven",
    "two-hundred-fifty-eight",
    "two-hundred-fifty-nine",
    "two-hundred-sixty",
    "two-hundred-sixty-one",
    "two-hundred-sixty-two",
    "two-hundred-sixty-three",
    "two-hundred-sixty-four",
    "two-hundred-sixty-five",
    "two-hundred-sixty-six",
    "two-hundred-sixty-seven",
    "two-hundred-sixty-eight",
    "two-hundred-sixty-nine",
    "two-hundred-seventy",
    "two-hundred-seventy-one",
    "two-hundred-seventy-two",
    "two-hundred-seventy-three",
    "two-hundred-seventy-four",
    "two-hundred-seventy-five",
    "two-hundred-seventy-six",
    "two-hundred-seventy-seven",
    "two-hundred-seventy-eight",
    "two-hundred-seventy-nine",
    "two-hundred-eighty",
    "two-hundred-eighty-one",
    "two-hundred-eighty-two",
    "two-hundred-eighty-three",
    "two-hundred-eighty-four",
    "two-hundred-eighty-five",
    "two-hundred-eighty-six",
    "two-hundred-eighty-seven",
    "two-hundred-eighty-eight",
    "two-hundred-eighty-nine",
    "two-hundred-ninety",
    "two-hundred-ninety-one",
    "two-hundred-ninety-two",
    "two-hundred-ninety-three",
    "two-hundred-ninety-four",
    "two-hundred-ninety-five",
    "two-hundred-ninety-six",
    "two-hundred-ninety-seven",
    "two-hundred-ninety-eight",
    "two-hundred-ninety-nine",
    "three-hundred",
    "three-hundred-one",
    "three-hundred-two",
    "three-hundred-three",
    "three-hundred-four",
    "three-hundred-five",
    "three-hundred-six",
    "three-hundred-seven",
    "three-hundred-eight",
    "three-hundred-nine",
    "three-hundred-ten",
    "three-hundred-eleven",
    "three-hundred-twelve",
    "three-hundred-thirteen",
    "three-hundred-fourteen",
    "three-hundred-fifteen",
    "three-hundred-sixteen",
    "three-hundred-seventeen",
    "three-hundred-eighteen",
    "three-hundred-nineteen",
    "three-hundred-twenty",
    "three-hundred-twenty-one",
    "three-hundred-twenty-two",
    "three-hundred-twenty-three",
    "three-hundred-twenty-four",
    "three-hundred-twenty-five",
    "three-hundred-twenty-six",
    "three-hundred-twenty-seven",
    "three-hundred-twenty-eight",
    "three-hundred-twenty-nine",
    "three-hundred-thirty",
    "three-hundred-thirty-one",
    "three-hundred-thirty-two",
    "three-hundred-thirty-three",
    "three-hundred-thirty-four",
    "three-hundred-thirty-five",
    "three-hundred-thirty-six",
    "three-hundred-thirty-seven",
    "three-hundred-thirty-eight",
    "three-hundred-thirty-nine",
    "three-hundred-forty",
    "three-hundred-forty-one",
    "three-hundred-forty-two",
    "three-hundred-forty-three",
    "three-hundred-forty-four",
    "three-hundred-forty-five",
    "three-hundred-forty-six",
    "three-hundred-forty-seven",
    "three-hundred-forty-eight",
    "three-hundred-forty-nine",
    "three-hundred-fifty",
    "three-hundred-fifty-one",
    "three-hundred-fifty-two",
    "three-hundred-fifty-three",
    "three-hundred-fifty-four",
    "three-hundred-fifty-five",
    "three-hundred-fifty-six",
    "three-hundred-fifty-seven",
    "three-hundred-fifty-eight",
    "three-hundred-fifty-nine",
    "three-hundred-sixty",
    "three-hundred-sixty-one",
    "three-hundred-sixty-two",
    "three-hundred-sixty-three",
    "three-hundred-sixty-four",
    "three-hundred-sixty-five",
    "three-hundred-sixty-six",
    "three-hundred-sixty-seven",
    "three-hundred-sixty-eight",
    "three-hundred-sixty-nine",
    "three-hundred-seventy",
    "three-hundred-seventy-one",
    "three-hundred-seventy-two",
    "three-hundred-seventy-three",
    "three-hundred-seventy-four",
    "three-hundred-seventy-five",
    "three-hundred-seventy-six",
    "three-hundred-seventy-seven",
    "three-hundred-seventy-eight",
    "three-hundred-seventy-nine",
    "three-hundred-eighty",
    "three-hundred-eighty-one",
    "three-hundred-eighty-two",
    "three-hundred-eighty-three",
    "three-hundred-eighty-four",
    "three-hundred-eighty-five",
    "three-hundred-eighty-six",
    "three-hundred-eighty-seven",
    "three-hundred-eighty-eight",
    "three-hundred-eighty-nine",
    "three-hundred-ninety",
    "three-hundred-ninety-one",
    "three-hundred-ninety-two",
    "three-hundred-ninety-three",
    "three-hundred-ninety-four",
    "three-hundred-ninety-five",
    "three-hundred-ninety-six",
    "three-hundred-ninety-seven",
    "three-hundred-ninety-eight",
    "three-hundred-ninety-nine",
    "four-hundred",
    "four-hundred-one",
    "four-hundred-two",
    "four-hundred-three",
    "four-hundred-four",
    "four-hundred-five",
    "four-hundred-six",
    "four-hundred-seven",
    "four-hundred-eight",
    "four-hundred-nine",
    "four-hundred-ten",
    "four-hundred-eleven",
    "four-hundred-twelve",
    "four-hundred-thirteen",
    "four-hundred-fourteen",
    "four-hundred-fifteen",
    "four-hundred-sixteen",
    "four-hundred-seventeen",
    "four-hundred-eighteen",
    "four-hundred-nineteen",
    "four-hundred-twenty",
    "four-hundred-twenty-one",
    "four-hundred-twenty-two",
    "four-hundred-twenty-three",
    "four-hundred-twenty-four",
    "four-hundred-twenty-five",
    "four-hundred-twenty-six",
    "four-hundred-twenty-seven",
    "four-hundred-twenty-eight",
    "four-hundred-twenty-nine",
    "four-hundred-thirty",
    "four-hundred-thirty-one",
    "four-hundred-thirty-two",
    "four-hundred-thirty-three",
    "four-hundred-thirty-four",
    "four-hundred-thirty-five",
    "four-hundred-thirty-six",
    "four-hundred-thirty-seven",
    "four-hundred-thirty-eight",
    "four-hundred-thirty-nine",
    "four-hundred-forty",
    "four-hundred-forty-one",
    "four-hundred-forty-two",
    "four-hundred-forty-three",
    "four-hundred-forty-four",
    "four-hundred-forty-five",
    "four-hundred-forty-six",
    "four-hundred-forty-seven",
    "four-hundred-forty-eight",
    "four-hundred-forty-nine",
    "four-hundred-fifty",
    "four-hundred-fifty-one",
    "four-hundred-fifty-two",
    "four-hundred-fifty-three",
    "four-hundred-fifty-four",
    "four-hundred-fifty-five",
    "four-hundred-fifty-six",
    "four-hundred-fifty-seven",
    "four-hundred-fifty-eight",
    "four-hundred-fifty-nine",
    "four-hundred-sixty",
    "four-hundred-sixty-one",
    "four-hundred-sixty-two",
    "four-hundred-sixty-three",
    "four-hundred-sixty-four",
    "four-hundred-sixty-five",
    "four-hundred-sixty-six",
    "four-hundred-sixty-seven",
    "four-hundred-sixty-eight",
    "four-hundred-sixty-nine",
    "four-hundred-seventy",
    "four-hundred-seventy-one",
    "four-hundred-seventy-two",
    "four-hundred-seventy-three",
    "four-hundred-seventy-four",
    "four-hundred-seventy-five",
    "four-hundred-seventy-six",
    "four-hundred-seventy-seven",
    "four-hundred-seventy-eight",
    "four-hundred-seventy-nine",
    "four-hundred-eighty",
    "four-hundred-eighty-one",
    "four-hundred-eighty-two",
    "four-hundred-eighty-three",
    "four-hundred-eighty-four",
    "four-hundred-eighty-five",
    "four-hundred-eighty-six",
    "four-hundred-eighty-seven",
    "four-hundred-eighty-eight",
    "four-hundred-eighty-nine",
    "four-hundred-ninety",
    "four-hundred-ninety-one",
    "four-hundred-ninety-two",
    "four-hundred-ninety-three",
    "four-hundred-ninety-four",
    "four-hundred-ninety-five",
    "four-hundred-ninety-six",
    "four-hundred-ninety-seven",
    "four-hundred-ninety-eight",
    "four-hundred-ninety-nine",
    "five-hundred",
    "five-hundred-one",
    "five-hundred-two",
    "five-hundred-three",
    "five-hundred-four",
    "five-hundred-five",
    "five-hundred-six",
    "five-hundred-seven",
    "five-hundred-eight",
    "five-hundred-nine",
    "five-hundred-ten",
    "five-hundred-eleven",
    "five-hundred-twelve",
    "five-hundred-thirteen",
    "five-hundred-fourteen",
    "five-hundred-fifteen",
    "five-hundred-sixteen",
    "five-hundred-seventeen",
    "five-hundred-eighteen",
    "five-hundred-nineteen",
    "five-hundred-twenty",
    "five-hundred-twenty-one",
    "five-hundred-twenty-two",
    "five-hundred-twenty-three",
    "five-hundred-twenty-four",
    "five-hundred-twenty-five",
    "five-hundred-twenty-six",
    "five-hundred-twenty-seven",
    "five-hundred-twenty-eight",
    "five-hundred-twenty-nine",
    "five-hundred-thirty",
    "five-hundred-thirty-one",
    "five-hundred-thirty-two",
    "five-hundred-thirty-three",
    "five-hundred-thirty-four",
    "five-hundred-thirty-five",
    "five-hundred-thirty-six",
    "five-hundred-thirty-seven",
    "five-hundred-thirty-eight",
    "five-hundred-thirty-nine",
    "five-hundred-forty",
    "five-hundred-forty-one",
    "five-hundred-forty-two",
    "five-hundred-forty-three",
    "five-hundred-forty-four",
    "five-hundred-forty-five",
    "five-hundred-forty-six",
    "five-hundred-forty-seven",
    "five-hundred-forty-eight",
    "five-hundred-forty-nine",
    "five-hundred-fifty",
    "five-hundred-fifty-one",
    "five-hundred-fifty-two",
    "five-hundred-fifty-three",
    "five-hundred-fifty-four",
    "five-hundred-fifty-five",
    "five-hundred-fifty-six",
    "five-hundred-fifty-seven",
    "five-hundred-fifty-eight",
    "five-hundred-fifty-nine",
    "five-hundred-sixty",
    "five-hundred-sixty-one",
    "five-hundred-sixty-two",
    "five-hundred-sixty-three",
    "five-hundred-sixty-four",
    "five-hundred-sixty-five",
    "five-hundred-sixty-six",
    "five-hundred-sixty-seven",
    "five-hundred-sixty-eight",
    "five-hundred-sixty-nine",
    "five-hundred-seventy",
    "five-hundred-seventy-one",
    "five-hundred-seventy-two",
    "five-hundred-seventy-three",
    "five-hundred-seventy-four",
    "five-hundred-seventy-five",
    "five-hundred-seventy-six",
    "five-hundred-seventy-seven",
    "five-hundred-seventy-eight",
    "five-hundred-seventy-nine",
    "five-hundred-eighty",
    "five-hundred-eighty-one",
    "five-hundred-eighty-two",
    "five-hundred-eighty-three",
    "five-hundred-eighty-four",
    "five-hundred-eighty-five",
    "five-hundred-eighty-six",
    "five-hundred-eighty-seven",
    "five-hundred-eighty-eight",
    "five-hundred-eighty-nine",
    "five-hundred-ninety",
    "five-hundred-ninety-one",
    "five-hundred-ninety-two",
    "five-hundred-ninety-three",
    "five-hundred-ninety-four",
    "five-hundred-ninety-five",
    "five-hundred-ninety-six",
    "five-hundred-ninety-seven",
    "five-hundred-ninety-eight",
    "five-hundred-ninety-nine",
    "six-hundred",
    "six-hundred-one",
    "six-hundred-two",
    "six-hundred-three",
    "six-hundred-four",
    "six-hundred-five",
    "six-hundred-six",
    "six-hundred-seven",
    "six-hundred-eight",
    "six-hundred-nine",
    "six-hundred-ten",
    "six-hundred-eleven",
    "six-hundred-twelve",
    "six-hundred-thirteen",
    "six-hundred-fourteen",
    "six-hundred-fifteen",
    "six-hundred-sixteen",
    "six-hundred-seventeen",
    "six-hundred-eighteen",
    "six-hundred-nineteen",
    "six-hundred-twenty",
    "six-hundred-twenty-one",
    "six-hundred-twenty-two",
    "six-hundred-twenty-three",
    "six-hundred-twenty-four",
    "six-hundred-twenty-five",
    "six-hundred-twenty-six",
    "six-hundred-twenty-seven",
    "six-hundred-twenty-eight",
    "six-hundred-twenty-nine",
    "six-hundred-thirty",
    "six-hundred-thirty-one",
    "six-hundred-thirty-two",
    "six-hundred-thirty-three",
    "six-hundred-thirty-four",
    "six-hundred-thirty-five",
    "six-hundred-thirty-six",
    "six-hundred-thirty-seven",
    "six-hundred-thirty-eight",
    "six-hundred-thirty-nine",
    "six-hundred-forty",
    "six-hundred-forty-one",
    "six-hundred-forty-two",
    "six-hundred-forty-three",
    "six-hundred-forty-four",
    "six-hundred-forty-five",
    "six-hundred-forty-six",
    "six-hundred-forty-seven",
    "six-hundred-forty-eight",
    "six-hundred-forty-nine",
    "six-hundred-fifty",
    "six-hundred-fifty-one",
    "six-hundred-fifty-two",
    "six-hundred-fifty-three",
    "six-hundred-fifty-four",
    "six-hundred-fifty-five",
    "six-hundred-fifty-six",
    "six-hundred-fifty-seven",
    "six-hundred-fifty-eight",
    "six-hundred-fifty-nine",
    "six-hundred-sixty",
    "six-hundred-sixty-one",
    "six-hundred-sixty-two",
    "six-hundred-sixty-three",
    "six-hundred-sixty-four",
    "six-hundred-sixty-five",
    "six-hundred-sixty-six",
    "six-hundred-sixty-seven",
    "six-hundred-sixty-eight",
    "six-hundred-sixty-nine",
    "six-hundred-seventy",
    "six-hundred-seventy-one",
    "six-hundred-seventy-two",
    "six-hundred-seventy-three",
    "six-hundred-seventy-four",
    "six-hundred-seventy-five",
    "six-hundred-seventy-six",
    "six-hundred-seventy-seven",
    "six-hundred-seventy-eight",
    "six-hundred-seventy-nine",
    "six-hundred-eighty",
    "six-hundred-eighty-one",
    "six-hundred-eighty-two",
    "six-hundred-eighty-three",
    "six-hundred-eighty-four",
    "six-hundred-eighty-five",
    "six-hundred-eighty-six",
    "six-hundred-eighty-seven",
    "six-hundred-eighty-eight",
    "six-hundred-eighty-nine",
    "six-hundred-ninety",
    "six-hundred-ninety-one",
    "six-hundred-ninety-two",
    "six-hundred-ninety-three",
    "six-hundred-ninety-four",
    "six-hundred-ninety-five",
    "six-hundred-ninety-six",
    "six-hundred-ninety-seven",
    "six-hundred-ninety-eight",
    "six-hundred-ninety-nine",
    "seven-hundred",
    "seven-hundred-one",
    "seven-hundred-two",
    "seven-hundred-three",
    "seven-hundred-four",
    "seven-hundred-five",
    "seven-hundred-six",
    "seven-hundred-seven",
    "seven-hundred-eight",
    "seven-hundred-nine",
    "seven-hundred-ten",
    "seven-hundred-eleven",
    "seven-hundred-twelve",
    "seven-hundred-thirteen",
    "seven-hundred-fourteen",
    "seven-hundred-fifteen",
    "seven-hundred-sixteen",
    "seven-hundred-seventeen",
    "seven-hundred-eighteen",
    "seven-hundred-nineteen",
    "seven-hundred-twenty",
    "seven-hundred-twenty-one",
    "seven-hundred-twenty-two",
    "seven-hundred-twenty-three",
    "seven-hundred-twenty-four",
    "seven-hundred-twenty-five",
    "seven-hundred-twenty-six",
    "seven-hundred-twenty-seven",
    "seven-hundred-twenty-eight",
    "seven-hundred-twenty-nine",
    "seven-hundred-thirty",
    "seven-hundred-thirty-one",
    "seven-hundred-thirty-two",
    "seven-hundred-thirty-three",
    "seven-hundred-thirty-four",
    "seven-hundred-thirty-five",
    "seven-hundred-thirty-six",
    "seven-hundred-thirty-seven",
    "seven-hundred-thirty-eight",
    "seven-hundred-thirty-nine",
    "seven-hundred-forty",
    "seven-hundred-forty-one",
    "seven-hundred-forty-two",
    "seven-hundred-forty-three",
    "seven-hundred-forty-four",
    "seven-hundred-forty-five",
    "seven-hundred-forty-six",
    "seven-hundred-forty-seven",
    "seven-hundred-forty-eight",
    "seven-hundred-forty-nine",
    "seven-hundred-fifty",
    "seven-hundred-fifty-one",
    "seven-hundred-fifty-two",
    "seven-hundred-fifty-three",
    "seven-hundred-fifty-four",
    "seven-hundred-fifty-five",
    "seven-hundred-fifty-six",
    "seven-hundred-fifty-seven",
    "seven-hundred-fifty-eight",
    "seven-hundred-fifty-nine",
    "seven-hundred-sixty",
    "seven-hundred-sixty-one",
    "seven-hundred-sixty-two",
    "seven-hundred-sixty-three",
    "seven-hundred-sixty-four",
    "seven-hundred-sixty-five",
    "seven-hundred-sixty-six",
    "seven-hundred-sixty-seven",
    "seven-hundred-sixty-eight",
    "seven-hundred-sixty-nine",
    "seven-hundred-seventy",
    "seven-hundred-seventy-one",
    "seven-hundred-seventy-two",
    "seven-hundred-seventy-three",
    "seven-hundred-seventy-four",
    "seven-hundred-seventy-five",
    "seven-hundred-seventy-six",
    "seven-hundred-seventy-seven",
    "seven-hundred-seventy-eight",
    "seven-hundred-seventy-nine",
    "seven-hundred-eighty",
    "seven-hundred-eighty-one",
    "seven-hundred-eighty-two",
    "seven-hundred-eighty-three",
    "seven-hundred-eighty-four",
    "seven-hundred-eighty-five",
    "seven-hundred-eighty-six",
    "seven-hundred-eighty-seven",
    "seven-hundred-eighty-eight",
    "seven-hundred-eighty-nine",
    "seven-hundred-ninety",
    "seven-hundred-ninety-one",
    "seven-hundred-ninety-two",
    "seven-hundred-ninety-three",
    "seven-hundred-ninety-four",
    "seven-hundred-ninety-five",
    "seven-hundred-ninety-six",
    "seven-hundred-ninety-seven",
    "seven-hundred-ninety-eight",
    "seven-hundred-ninety-nine",
    "eight-hundred",
    "eight-hundred-one",
    "eight-hundred-two",
    "eight-hundred-three",
    "eight-hundred-four",
    "eight-hundred-five",
    "eight-hundred-six",
    "eight-hundred-seven",
    "eight-hundred-eight",
    "eight-hundred-nine",
    "eight-hundred-ten",
    "eight-hundred-eleven",
    "eight-hundred-twelve",
    "eight-hundred-thirteen",
    "eight-hundred-fourteen",
    "eight-hundred-fifteen",
    "eight-hundred-sixteen",
    "eight-hundred-seventeen",
    "eight-hundred-eighteen",
    "eight-hundred-nineteen",
    "eight-hundred-twenty",
    "eight-hundred-twenty-one",
    "eight-hundred-twenty-two",
    "eight-hundred-twenty-three",
    "eight-hundred-twenty-four",
    "eight-hundred-twenty-five",
    "eight-hundred-twenty-six",
    "eight-hundred-twenty-seven",
    "eight-hundred-twenty-eight",
    "eight-hundred-twenty-nine",
    "eight-hundred-thirty",
    "eight-hundred-thirty-one",
    "eight-hundred-thirty-two",
    "eight-hundred-thirty-three",
    "eight-hundred-thirty-four",
    "eight-hundred-thirty-five",
    "eight-hundred-thirty-six",
    "eight-hundred-thirty-seven",
    "eight-hundred-thirty-eight",
    "eight-hundred-thirty-nine",
    "eight-hundred-forty",
    "eight-hundred-forty-one",
    "eight-hundred-forty-two",
    "eight-hundred-forty-three",
    "eight-hundred-forty-four",
    "eight-hundred-forty-five",
    "eight-hundred-forty-six",
    "eight-hundred-forty-seven",
    "eight-hundred-forty-eight",
    "eight-hundred-forty-nine",
    "eight-hundred-fifty",
    "eight-hundred-fifty-one",
    "eight-hundred-fifty-two",
    "eight-hundred-fifty-three",
    "eight-hundred-fifty-four",
    "eight-hundred-fifty-five",
    "eight-hundred-fifty-six",
    "eight-hundred-fifty-seven",
    "eight-hundred-fifty-eight",
    "eight-hundred-fifty-nine",
    "eight-hundred-sixty",
    "eight-hundred-sixty-one",
    "eight-hundred-sixty-two",
    "eight-hundred-sixty-three",
    "eight-hundred-sixty-four",
    "eight-hundred-sixty-five",
    "eight-hundred-sixty-six",
    "eight-hundred-sixty-seven",
    "eight-hundred-sixty-eight",
    "eight-hundred-sixty-nine",
    "eight-hundred-seventy",
    "eight-hundred-seventy-one",
    "eight-hundred-seventy-two",
    "eight-hundred-seventy-three",
    "eight-hundred-seventy-four",
    "eight-hundred-seventy-five",
    "eight-hundred-seventy-six",
    "eight-hundred-seventy-seven",
    "eight-hundred-seventy-eight",
    "eight-hundred-seventy-nine",
    "eight-hundred-eighty",
    "eight-hundred-eighty-one",
    "eight-hundred-eighty-two",
    "eight-hundred-eighty-three",
    "eight-hundred-eighty-four",
    "eight-hundred-eighty-five",
    "eight-hundred-eighty-six",
    "eight-hundred-eighty-seven",
    "eight-hundred-eighty-eight",
    "eight-hundred-eighty-nine",
    "eight-hundred-ninety",
    "eight-hundred-ninety-one",
    "eight-hundred-ninety-two",
    "eight-hundred-ninety-three",
    "eight-hundred-ninety-four",
    "eight-hundred-ninety-five",
    "eight-hundred-ninety-six",
    "eight-hundred-ninety-seven",
    "eight-hundred-ninety-eight",
    "eight-hundred-ninety-nine",
    "nine-hundred",
    "nine-hundred-one",
    "nine-hundred-two",
    "nine-hundred-three",
    "nine-hundred-four",
    "nine-hundred-five",
    "nine-hundred-six",
    "nine-hundred-seven",
    "nine-hundred-eight",
    "nine-hundred-nine",
    "nine-hundred-ten",
    "nine-hundred-eleven",
    "nine-hundred-twelve",
    "nine-hundred-thirteen",
    "nine-hundred-fourteen",
    "nine-hundred-fifteen",
    "nine-hundred-sixteen",
    "nine-hundred-seventeen",
    "nine-hundred-eighteen",
    "nine-hundred-nineteen",
    "nine-hundred-twenty",
    "nine-hundred-twenty-one",
    "nine-hundred-twenty-two",
    "nine-hundred-twenty-three",
    "nine-hundred-twenty-four",
    "nine-hundred-twenty-five",
    "nine-hundred-twenty-six",
    "nine-hundred-twenty-seven",
    "nine-hundred-twenty-eight",
    "nine-hundred-twenty-nine",
    "nine-hundred-thirty",
    "nine-hundred-thirty-one",
    "nine-hundred-thirty-two",
    "nine-hundred-thirty-three",
    "nine-hundred-thirty-four",
    "nine-hundred-thirty-five",
    "nine-hundred-thirty-six",
    "nine-hundred-thirty-seven",
    "nine-hundred-thirty-eight",
    "nine-hundred-thirty-nine",
    "nine-hundred-forty",
    "nine-hundred-forty-one",
    "nine-hundred-forty-two",
    "nine-hundred-forty-three",
    "nine-hundred-forty-four",
    "nine-hundred-forty-five",
    "nine-hundred-forty-six",
    "nine-hundred-forty-seven",
    "nine-hundred-forty-eight",
    "nine-hundred-forty-nine",
    "nine-hundred-fifty",
    "nine-hundred-fifty-one",
    "nine-hundred-fifty-two",
    "nine-hundred-fifty-three",
    "nine-hundred-fifty-four",
    "nine-hundred-fifty-five",
    "nine-hundred-fifty-six",
    "nine-hundred-fifty-seven",
    "nine-hundred-fifty-eight",
    "nine-hundred-fifty-nine",
    "nine-hundred-sixty",
    "nine-hundred-sixty-one",
    "nine-hundred-sixty-two",
    "nine-hundred-sixty-three",
    "nine-hundred-sixty-four",
    "nine-hundred-sixty-five",
    "nine-hundred-sixty-six",
    "nine-hundred-sixty-seven",
    "nine-hundred-sixty-eight",
    "nine-hundred-sixty-nine",
    "nine-hundred-seventy",
    "nine-hundred-seventy-one",
    "nine-hundred-seventy-two",
    "nine-hundred-seventy-three",
    "nine-hundred-seventy-four",
    "nine-hundred-seventy-five",
    "nine-hundred-seventy-six",
    "nine-hundred-seventy-seven",
    "nine-hundred-seventy-eight",
    "nine-hundred-seventy-nine",
    "nine-hundred-eighty",
    "nine-hundred-eighty-one",
    "nine-hundred-eighty-two",
    "nine-hundred-eighty-three",
    "nine-hundred-eighty-four",
    "nine-hundred-eighty-five",
    "nine-hundred-eighty-six",
    "nine-hundred-eighty-seven",
    "nine-hundred-eighty-eight",
    "nine-hundred-eighty-nine",
    "nine-hundred-ninety",
    "nine-hundred-ninety-one",
    "nine-hundred-ninety-two",
    "nine-hundred-ninety-three",
    "nine-hundred-ninety-four",
    "nine-hundred-ninety-five",
    "nine-hundred-ninety-six",
    "nine-hundred-ninety-seven",
    "nine-hundred-ninety-eight",
    "nine-hundred-ninety-nine",
    "one-thousand",
  ],
  enVerbs: [
    "accept",
    "allow",
    "ask",
    "be",
    "become",
    "begin",
    "call",
    "can",
    "come",
    "consider",
    "continue",
    "could",
    "create",
    "cut",
    "do",
    "drive",
    "eat",
    "feel",
    "find",
    "get",
    "give",
    "go",
    "grow",
    "have",
    "hear",
    "help",
    "hold",
    "keep",
    "know",
    "learn",
    "leave",
    "like",
    "live",
    "look",
    "make",
    "mean",
    "might",
    "move",
    "need",
    "open",
    "play",
    "put",
    "read",
    "run",
    "say",
    "see",
    "seem",
    "should",
    "show",
    "sit",
    "sleep",
    "smell",
    "speak",
    "stand",
    "start",
    "stay",
    "stop",
    "take",
    "talk",
    "tell",
    "think",
    "try",
    "turn",
    "understand",
    "use",
    "wait",
    "walk",
    "want",
    "watch",
    "will",
    "win",
    "work",
    "would",
    "write",
    "jump",
    "listen",
    "lose",
    "remember",
    "send",
    "buy",
    "admire",
    "advise",
    "afford",
    "agree",
    "announce",
    "apologize",
    "appear",
    "approve",
    "argue",
    "arrive",
    "attach",
    "attack",
    "avoid",
    "bake",
    "balance",
    "ban",
    "bang",
    "bathe",
    "behave",
    "believe",
    "bless",
    "blink",
    "boil",
    "borrow",
    "bounce",
    "bow",
    "brake",
    "breathe",
    "brush",
    "buzz",
    "calculate",
    "call",
    "camp",
    "care",
    "carry",
    "catch",
    "challenge",
    "change",
    "charge",
    "cheat",
    "cheer",
    "choke",
    "claim",
    "clap",
    "clean",
    "clear",
    "climb",
    "clip",
    "close",
    "coach",
    "coil",
    "collect",
    "color",
    "comb",
    "complain",
    "concentrate",
    "confess",
    "confuse",
    "connect",
    "consider",
    "consist",
    "contain",
    "continue",
    "copy",
    "correct",
    "count",
    "cover",
    "crack",
    "crawl",
    "cross",
    "cry",
    "curl",
  ],
  enAdj: [
    "happy",
    "sad",
    "angry",
    "bright",
    "dark",
    "beautiful",
    "ugly",
    "big",
    "small",
    "fast",
    "slow",
    "strong",
    "weak",
    "hot",
    "cold",
    "new",
    "old",
    "young",
    "tall",
    "short",
    "clean",
    "dirty",
    "easy",
    "difficult",
    "expensive",
    "cheap",
    "friendly",
    "mean",
    "funny",
    "serious",
    "brave",
    "calm",
    "careful",
    "careless",
    "clever",
    "clumsy",
    "comfortable",
    "dangerous",
    "deep",
    "dry",
    "early",
    "famous",
    "fat",
    "friendly",
    "gentle",
    "great",
    "happy",
    "healthy",
    "heavy",
    "honest",
    "important",
    "kind",
    "lazy",
    "light",
    "little",
    "long",
    "loud",
    "modern",
    "natural",
    "neat",
    "nice",
    "noisy",
    "old",
    "polite",
    "popular",
    "powerful",
    "quiet",
    "real",
    "rich",
    "safe",
    "serious",
    "shy",
    "simple",
    "slow",
    "soft",
    "strong",
    "sweet",
    "tall",
    "thin",
    "useful",
    "abundant",
    "aggressive",
    "ancient",
    "anxious",
    "arrogant",
    "awful",
    "bare",
    "bitter",
    "bland",
    "blurry",
    "bold",
    "bouncy",
    "bright",
    "brisk",
    "broken",
    "bumpy",
    "carefree",
    "charming",
    "cheerful",
    "chilly",
    "classic",
    "clean",
    "clear",
    "clumsy",
    "coarse",
    "colorful",
    "complex",
    "concise",
    "constant",
    "cool",
    "courageous",
    "crazy",
    "creamy",
    "creepy",
    "crisp",
    "crooked",
    "cruel",
    "curly",
    "cute",
    "damp",
    "dangerous",
    "dark",
    "dazzling",
    "dead",
    "deafening",
    "decent",
    "deep",
    "defiant",
    "delicate",
    "delicious",
    "diligent",
    "dim",
    "dirty",
    "disgusting",
    "dizzy",
    "dramatic",
    "dreary",
    "dull",
    "eager",
    "early",
    "earnest",
    "easy",
    "elastic",
    "electric",
    "elegant",
    "empty",
    "enormous",
    "enthusiastic",
    "evil",
    "faint",
    "fair",
    "faithful",
    "fancy",
  ],
  faVerbs: [
    "رفت",
    "آمد",
    "خورد",
    "نوشید",
    "دید",
    "شنید",
    "گفت",
    "نوشت",
    "خواند",
    "نشست",
    "خوابید",
    "بیدار شد",
    "دوید",
    "ایستاد",
    "نشاند",
    "ساخت",
    "شکست",
    "خرید",
    "فروخت",
    "گذاشت",
    "برداشت",
    "آمد",
    "رفت",
    "پرسید",
    "جواب داد",
    "خواست",
    "توانست",
    "فهمید",
    "گفت‌وگو کرد",
    "کمک کرد",
    "بازی کرد",
    "درس خواند",
    "کار کرد",
    "شنا کرد",
    "دوچرخه‌سواری کرد",
    "رانندگی کرد",
    "پخت",
    "شست",
    "زد",
    "گرفت",
    "انداخت",
    "پوشید",
    "برداشت",
    "بست",
    "باز کرد",
    "شروع کرد",
    "تمام کرد",
    "یاد گرفت",
    "فراموش کرد",
    "خندید",
    "گریه کرد",
    "آواز خواند",
    "رقصید",
    "فکر کرد",
    "امید داشت",
    "صبر کرد",
    "انتظار کشید",
    "باور کرد",
    "ترک کرد",
    "برگشت",
    "منتظر ماند",
    "انتخاب کرد",
    "ادامه داد",
    "متوقف شد",
    "چرخید",
    "گشت",
    "شناساند",
    "حمایت کرد",
    "تصور کرد",
    "تجربه کرد",
    "تغییر داد",
    "نوشید",
    "پذیرفت",
    "مخالفت کرد",
    "تمرین کرد",
    "حرکت کرد",
    "شناخت",
    "دیدار کرد",
    "ملاقات کرد",
    "تصمیم گرفت",
    "آماده شد",
    "جستجو کرد",
    "دریافت کرد",
    "ارسال کرد",
    "دریافت کرد",
    "قبول کرد",
    "آموخت",
    "آورد",
    "آغاز کرد",
    "ابراز کرد",
    "اجازه داد",
    "اعلام کرد",
    "انتقاد کرد",
    "انتقال داد",
    "انجام داد",
    "انباشت",
    "اندیشید",
    "اوضاع داد",
    "ایجاد کرد",
    "بازدید کرد",
    "بازگشت",
    "برجسته شد",
    "برخورد کرد",
    "برنامه‌ریزی کرد",
    "برنده شد",
    "بخشید",
    "بیان کرد",
    "پاسخ داد",
    "پذیرفت",
    "پیشرفت کرد",
    "تایید کرد",
    "تعریف کرد",
    "تغییر داد",
    "تمرکز کرد",
    "تحسین کرد",
    "تحقیق کرد",
    "تحویل داد",
    "تصمیم گرفت",
    "تصور کرد",
    "تغذیه کرد",
    "تکرار کرد",
    "تلاش کرد",
    "توضیح داد",
    "ثبت کرد",
    "تسلیم شد",
    "تکمیل کرد",
    "جمع‌آوری کرد",
    "جستجو کرد",
    "جدید شد",
    "جلوگیری کرد",
    "چرخید",
    "حذف کرد",
    "حفظ کرد",
    "حمایت کرد",
    "حرکت کرد",
    "حمله کرد",
    "حضور داشت",
    "خارج شد",
    "خرید",
    "خراب کرد",
    "خوابید",
    "خندید",
    "دست زد",
    "دنبال کرد",
    "داوطلب شد",
    "دریافت کرد",
    "دوید",
    "رشد کرد",
    "رفت",
    "رزرو کرد",
    "زد",
    "زنده ماند",
    "سریع رفت",
    "سازگار شد",
    "ساخت",
    "سوء استفاده کرد",
    "سرگرم شد",
    "شکست خورد",
    "شکست داد",
    "شناخت",
    "شناسایی کرد",
    "شروع کرد",
    "صدا زد",
    "صبر کرد",
    "ضربه زد",
    "عمل کرد",
    "غذا خورد",
    "فروخت",
    "فکر کرد",
    "فعال شد",
  ],
  faAdj: [
    "زیبا",
    "زشت",
    "بزرگ",
    "کوچک",
    "سریع",
    "کند",
    "قوی",
    "ضعیف",
    "داغ",
    "سرد",
    "جدید",
    "قدیمی",
    "جوان",
    "بلند",
    "کوتاه",
    "تمیز",
    "کثیف",
    "آسان",
    "سخت",
    "گران",
    "ارزان",
    "دوست‌داشتنی",
    "بدجنس",
    "خنده‌دار",
    "جدی",
    "شجاع",
    "آرام",
    "مراقب",
    "بی‌مراقبت",
    "باهوش",
    "دست‌وپاچلفتی",
    "راحت",
    "خطرناک",
    "عمیق",
    "خشک",
    "زود",
    "مشهور",
    "چاق",
    "مهربان",
    "لطیف",
    "عالی",
    "سالم",
    "سنگین",
    "صادق",
    "مهم",
    "مهربان",
    "تنبل",
    "سبک",
    "کوچک",
    "طولانی",
    "بلندصدا",
    "مدرن",
    "طبیعی",
    "مرتب",
    "خوب",
    "پرصدا",
    "مودب",
    "محبوب",
    "قوی",
    "ساکت",
    "واقعی",
    "ثروتمند",
    "امن",
    "جدی",
    "خجالتی",
    "ساده",
    "کند",
    "نرم",
    "قوی",
    "شیرین",
    "بلندقد",
    "لاغر",
    "مفید",
    "پرکار",
    "بی‌کار",
    "خوشحال",
    "غمگین",
    "شاد",
    "ناراحت",
    "خوب‌خلق",
    "بدخلق",
    "دقیق",
    "بی‌دقت",
    "صبور",
    "بی‌صبر",
    "مهربان",
    "بی‌رحم",
    "باهوش",
    "کندذهن",
    "فعال",
    "تنبل",
    "منظم",
    "نامنظم",
    "باهوش",
    "بی‌توجه",
    "باهوش",
    "بی‌ادب",
    "سخت‌کوش",
    "تنبل",
    "خوش‌صدا",
    "بیسروصدا",
    "پررنگ",
    "کمرنگ",
    "سردمزاج",
    "گرم‌مزاج",
    "خشن",
    "ملایم",
    "باهوش",
    "بی‌هوش",
    "قوی",
    "ضعیف",
    "پرانرژی",
    "بی‌انرژی",
    "صادق",
    "دروغگو",
    "ظریف",
    "درشت",
    "باهوش",
    "بی‌فکر",
    "خوش‌بین",
    "بدبین",
    "مغرور",
    "متواضع",
    "صبور",
    "عجول",
    "خوش‌شانس",
    "بدشانس",
    "زیبا",
    "زشت",
    "محتاط",
    "بی‌ملاحظه",
    "شاداب",
    "پرتلاش",
    "باهوش",
    "بی‌دقت",
    "مودب",
    "بی‌ادب",
    "پرحرف",
    "کم‌حرف",
    "دوست‌داشتنی",
    "تنها",
    "خوش‌اخلاق",
    "بدخلق",
    "خوش‌اندام",
    "لاغراندام",
  ],
};
module.exports = WordsMap;
